spring.application.name=techstore
spring.datasource.url=jdbc:postgresql://localhost:5433/techstore
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.sql.init.mode=always
